blank_issues_enabled: false

contact_links:
  - name: Questions & Discussions
    url: https://github.com/YummYume/Russia-2.0/discussions
    about: Ask questions and start discussions here.
  - name: Community Chat (Discord)
    url: https://discord.gg/xf5PUxK
    about: Join our community chat.
