# Created by Yam for the Russia Reworked mod. Free to use.
import traceback

if __name__ == "__main__":

    try:
        national_obligations = [
            "industrial_awakening",
            "tsar_bomba",
            "unfailing_army",
            "grand_fleet",
            "proletarian_union",
            "neverending_story",
            "continental_system",
            "treaty_moscow",
            "golden_age",
            "imperial_obligations",
            "carry_on_legacy",
            "russian_realm",
            "rebirth"
        ]
        national_obligations_options = [
            3,
            2,
            2,
            2,
            3,
            3,
            2,
            2,
            2,
            3,
            2,
            3,
            3,
        ]
        f = open("national_obligations_save.txt", "w", encoding='utf-8-sig')

        # All for statements are separated to avoid confusion
        print("Generating scripted loc...")
        scripted_loc = "# Generated by python script for Russia Reworked\n\n"
        scripted_loc += "# Scripted loc\n"
        scripted_loc += "defined_text = {\n"
        scripted_loc += "    name = GetCurrentSelectedIndexNationalObligations\n"

        i = 1
        for national_obligation in national_obligations:
            scripted_loc += "    text = {\n"
            scripted_loc += "        trigger = {\n"
            scripted_loc += "            THIS = {\n"
            scripted_loc += "                check_variable = {\n"
            scripted_loc += "                    sov_national_obligations_selected_index = %s\n" % i
            scripted_loc += "                }\n"
            scripted_loc += "            }\n"
            scripted_loc += "        }\n"
            scripted_loc += "        localization_key = GUI_NATIONAL_OBLIGATIONS_INDEX_%s_SELECTED\n" % i
            scripted_loc += "    }\n"
            i += 1

        scripted_loc += "    text = {\n"
        scripted_loc += "        localization_key = GUI_NATIONAL_OBLIGATIONS_INDEX_0_SELECTED\n"
        scripted_loc += "    }\n"
        scripted_loc += "}\n"

        f.write(scripted_loc)

        scripted_loc = "\ndefined_text = {\n"
        scripted_loc += "    name = GetCurrentSelectedIndexNationalObligationsTitle\n"

        i = 1
        for national_obligation in national_obligations:
            scripted_loc += "    text = {\n"
            scripted_loc += "        trigger = {\n"
            scripted_loc += "            THIS = {\n"
            scripted_loc += "                check_variable = {\n"
            scripted_loc += "                    sov_national_obligations_selected_index = %s\n" % i
            scripted_loc += "                }\n"
            scripted_loc += "            }\n"
            scripted_loc += "        }\n"
            scripted_loc += "        localization_key = GUI_NATIONAL_OBLIGATIONS_INDEX_%s_SELECTED_TITLE\n" % i
            scripted_loc += "    }\n"
            i += 1

        scripted_loc += "    text = {\n"
        scripted_loc += "        localization_key = GUI_NATIONAL_OBLIGATIONS_INDEX_0_SELECTED_TITLE\n"
        scripted_loc += "    }\n"
        scripted_loc += "}\n"

        f.write(scripted_loc)

        scripted_loc = "\ndefined_text = {\n"
        scripted_loc += "    name = GetCurrentSelectedIndexNationalObligationsIcon\n"

        i = 1
        for national_obligation in national_obligations:
            scripted_loc += "    text = {\n"
            scripted_loc += "        trigger = {\n"
            scripted_loc += "            THIS = {\n"
            scripted_loc += "                check_variable = {\n"
            scripted_loc += "                    sov_national_obligations_selected_index = %s\n" % i
            scripted_loc += "                }\n"
            scripted_loc += "            }\n"
            scripted_loc += "        }\n"
            scripted_loc += "        localization_key = GUI_NATIONAL_OBLIGATIONS_INDEX_%s_SELECTED_ICON\n" % i
            scripted_loc += "    }\n"
            i += 1

        scripted_loc += "    text = {\n"
        scripted_loc += "        localization_key = GUI_NATIONAL_OBLIGATIONS_INDEX_0_SELECTED_ICON\n"
        scripted_loc += "    }\n"
        scripted_loc += "}\n"

        f.write(scripted_loc)

        i = 1
        for national_obligation in national_obligations:
            title = national_obligation.replace("_", " ").title()
            print("Generating %s" % title)

            scripted_loc = "\n# %s\n" % title
            scripted_loc += "defined_text = {\n"
            scripted_loc += "    name = GetCurrentSelectedIndexNationalObligationsNav%s\n" % title.replace(" ", "")
            scripted_loc += "    text = {\n"
            scripted_loc += "        trigger = {\n"
            scripted_loc += "            THIS = {\n"
            scripted_loc += "                check_variable = {\n"
            scripted_loc += "                    sov_national_obligations_selected_index = %s\n" % i
            scripted_loc += "                }\n"
            scripted_loc += "            }\n"
            scripted_loc += "        }\n"
            scripted_loc += "        localization_key = GUI_NATIONAL_OBLIGATIONS_INDEX_NAV_SELECTED\n"
            scripted_loc += "    }\n"
            scripted_loc += "    text = {\n"
            scripted_loc += "        localization_key = GUI_NATIONAL_OBLIGATIONS_INDEX_NAV_NOT_SELECTED\n"
            scripted_loc += "    }\n"
            scripted_loc += "}\n\n"

            scripted_loc += "defined_text = {\n"
            scripted_loc += "    name = GetCurrentSelectedIndexNationalObligationsNav%sTitle\n" % title.replace(" ", "")
            scripted_loc += "    text = {\n"
            scripted_loc += "        trigger = {\n"
            scripted_loc += "            THIS = {\n"
            scripted_loc += "                check_variable = {\n"
            scripted_loc += "                    sov_national_obligations_selected_index = %s\n" % i
            scripted_loc += "                }\n"
            scripted_loc += "            }\n"
            scripted_loc += "        }\n"
            scripted_loc += "        localization_key = GUI_NATIONAL_OBLIGATIONS_%s_SELECTED\n" % national_obligation.upper()
            scripted_loc += "    }\n"
            scripted_loc += "    text = {\n"
            scripted_loc += "        trigger = {\n"
            scripted_loc += "            THIS = {\n"
            scripted_loc += "                is_in_array = { sov_national_obligations_unlocked_indexes = %s }\n" % i
            scripted_loc += "            }\n"
            scripted_loc += "        }\n"
            scripted_loc += "        localization_key = GUI_NATIONAL_OBLIGATIONS_%s_UNLOCKED\n" % national_obligation.upper()
            scripted_loc += "    }\n"
            scripted_loc += "    text = {\n"
            scripted_loc += "        localization_key = GUI_NATIONAL_OBLIGATIONS_%s_NOT_UNLOCKED\n" % national_obligation.upper()
            scripted_loc += "    }\n"
            scripted_loc += "}\n"
            i += 1

            f.write(scripted_loc)

        print("Success", end="\n\n")
        print("Generating localisation...")
        f.write("\n# Localisation\n")

        i = 1
        for national_obligation in national_obligations:
            loc = " GUI_NATIONAL_OBLIGATIONS_INDEX_%s_SELECTED:0 \"GFX_national_obligations_%s_gui\"\n" % (i, national_obligation)
            i += 1

            f.write(loc)

        i = 1
        for national_obligation in national_obligations:
            title = national_obligation.replace("_", " ").title()
            loc = " GUI_NATIONAL_OBLIGATIONS_INDEX_%s_SELECTED_TITLE:0 \"§O%s§!\"\n" % (i, title)
            i += 1

            f.write(loc)

        i = 1
        for national_obligation in national_obligations:
            loc = " GUI_NATIONAL_OBLIGATIONS_INDEX_%s_SELECTED_ICON:0 \"GFX_national_obligations_%s_icon\"\n" % (i, national_obligation)
            i += 1

            f.write(loc)

        i = 1
        for national_obligation in national_obligations:
            title = national_obligation.replace("_", " ").title()
            loc = " GUI_NATIONAL_OBLIGATIONS_%s_SELECTED:0 \"§O%s§!\"\n" % (national_obligation.upper(), title)
            loc += " GUI_NATIONAL_OBLIGATIONS_%s_UNLOCKED:0 \"§Y%s§!\"\n" % (national_obligation.upper(), title)
            loc += " GUI_NATIONAL_OBLIGATIONS_%s_NOT_UNLOCKED:0 \"§g%s§!\"\n" % (national_obligation.upper(), title)
            i += 1

            f.write(loc)

        i = 1
        for national_obligation in national_obligations:
            title = national_obligation.replace("_", " ").title()
            loc = " LOC_sov_national_obligations_nav_%s:0 \"[THIS.GetCurrentSelectedIndexNationalObligationsNav%sTitle]\"\n" % (national_obligation, title.replace(" ", ""))
            i += 1

            f.write(loc)

        print("Success", end="\n\n")
        print("Generating scripted gui...")
        f.write("\n# Scripted GUI")

        i = 1
        for national_obligation in national_obligations:
            title = national_obligation.replace("_", " ").title()
            scripted_gui = "\nsov_national_obligations_nav_%s = {\n" % (national_obligation)
            scripted_gui += "    image = [THIS.GetCurrentSelectedIndexNationalObligationsNav%s]\n" % (title.replace(" ", ""))
            scripted_gui += "}\n"
            i += 1

            f.write(scripted_gui)

        print("Success")
        f.close

    except Exception:
        print("Something went wrong...")
        print(traceback.format_exc())
