# Created by Yam for the Russia Reworked mod. Free to use. Requires Python 3.10
import traceback

if __name__ == "__main__":

    try:
        national_obligations = [
            "industrial_awakening",
            "tsar_bomba",
            "unfailing_army",
            "grand_fleet",
            "proletarian_union",
            "neverending_story",
            "continental_system",
            "treaty_moscow",
            "golden_age",
            "imperial_obligations",
            "carry_on_legacy",
            "russian_realm",
            "rebirth"
        ]
        national_obligations_options = [
            3,
            2,
            2,
            2,
            3,
            3,
            2,
            2,
            2,
            3,
            2,
            3,
            3,
        ]
        f = open("national_obligations_save.txt", "w", encoding='utf-8-sig')

        # All for statements are separated to avoid confusion
        print("Starting by generating navs and backgrounds")
        print("Generating scripted loc...")
        scripted_loc = "# Generated by python script for Russia Reworked\n\n"
        scripted_loc += "# Scripted loc\n"
        scripted_loc += "defined_text = {\n"
        scripted_loc += "    name = GetCurrentSelectedIndexNationalObligations\n"

        i = 1
        for national_obligation in national_obligations:
            scripted_loc += "    text = {\n"
            scripted_loc += "        trigger = {\n"
            scripted_loc += "            THIS = {\n"
            scripted_loc += "                check_variable = {\n"
            scripted_loc += "                    sov_national_obligations_selected_index = %s\n" % i
            scripted_loc += "                }\n"
            scripted_loc += "            }\n"
            scripted_loc += "        }\n"
            scripted_loc += "        localization_key = GUI_NATIONAL_OBLIGATIONS_INDEX_%s_SELECTED\n" % i
            scripted_loc += "    }\n"
            i += 1

        scripted_loc += "    text = {\n"
        scripted_loc += "        localization_key = GUI_NATIONAL_OBLIGATIONS_INDEX_0_SELECTED\n"
        scripted_loc += "    }\n"
        scripted_loc += "}\n"

        f.write(scripted_loc)

        scripted_loc = "\ndefined_text = {\n"
        scripted_loc += "    name = GetCurrentSelectedIndexNationalObligationsTitle\n"

        i = 1
        for national_obligation in national_obligations:
            scripted_loc += "    text = {\n"
            scripted_loc += "        trigger = {\n"
            scripted_loc += "            THIS = {\n"
            scripted_loc += "                check_variable = {\n"
            scripted_loc += "                    sov_national_obligations_selected_index = %s\n" % i
            scripted_loc += "                }\n"
            scripted_loc += "            }\n"
            scripted_loc += "        }\n"
            scripted_loc += "        localization_key = GUI_NATIONAL_OBLIGATIONS_INDEX_%s_SELECTED_TITLE\n" % i
            scripted_loc += "    }\n"
            i += 1

        scripted_loc += "    text = {\n"
        scripted_loc += "        localization_key = GUI_NATIONAL_OBLIGATIONS_INDEX_0_SELECTED_TITLE\n"
        scripted_loc += "    }\n"
        scripted_loc += "}\n"

        f.write(scripted_loc)

        scripted_loc = "\ndefined_text = {\n"
        scripted_loc += "    name = GetCurrentSelectedIndexNationalObligationsIcon\n"

        i = 1
        for national_obligation in national_obligations:
            scripted_loc += "    text = {\n"
            scripted_loc += "        trigger = {\n"
            scripted_loc += "            THIS = {\n"
            scripted_loc += "                check_variable = {\n"
            scripted_loc += "                    sov_national_obligations_selected_index = %s\n" % i
            scripted_loc += "                }\n"
            scripted_loc += "            }\n"
            scripted_loc += "        }\n"
            scripted_loc += "        localization_key = GUI_NATIONAL_OBLIGATIONS_INDEX_%s_SELECTED_ICON\n" % i
            scripted_loc += "    }\n"
            i += 1

        scripted_loc += "    text = {\n"
        scripted_loc += "        localization_key = GUI_NATIONAL_OBLIGATIONS_INDEX_0_SELECTED_ICON\n"
        scripted_loc += "    }\n"
        scripted_loc += "}\n"

        f.write(scripted_loc)

        i = 1
        for national_obligation in national_obligations:
            title = national_obligation.replace("_", " ").title()

            scripted_loc = "\n# %s\n" % title
            scripted_loc += "defined_text = {\n"
            scripted_loc += "    name = GetCurrentSelectedIndexNationalObligationsNav%s\n" % title.replace(" ", "")
            scripted_loc += "    text = {\n"
            scripted_loc += "        trigger = {\n"
            scripted_loc += "            THIS = {\n"
            scripted_loc += "                check_variable = {\n"
            scripted_loc += "                    sov_national_obligations_selected_index = %s\n" % i
            scripted_loc += "                }\n"
            scripted_loc += "            }\n"
            scripted_loc += "        }\n"
            scripted_loc += "        localization_key = GUI_NATIONAL_OBLIGATIONS_INDEX_NAV_SELECTED\n"
            scripted_loc += "    }\n"
            scripted_loc += "    text = {\n"
            scripted_loc += "        localization_key = GUI_NATIONAL_OBLIGATIONS_INDEX_NAV_NOT_SELECTED\n"
            scripted_loc += "    }\n"
            scripted_loc += "}\n\n"

            scripted_loc += "defined_text = {\n"
            scripted_loc += "    name = GetCurrentSelectedIndexNationalObligationsNav%sTitle\n" % title.replace(" ", "")
            scripted_loc += "    text = {\n"
            scripted_loc += "        trigger = {\n"
            scripted_loc += "            THIS = {\n"
            scripted_loc += "                check_variable = {\n"
            scripted_loc += "                    sov_national_obligations_selected_index = %s\n" % i
            scripted_loc += "                }\n"
            scripted_loc += "            }\n"
            scripted_loc += "        }\n"
            scripted_loc += "        localization_key = GUI_NATIONAL_OBLIGATIONS_%s_SELECTED\n" % national_obligation.upper()
            scripted_loc += "    }\n"
            scripted_loc += "    text = {\n"
            scripted_loc += "        trigger = {\n"
            scripted_loc += "            THIS = {\n"
            scripted_loc += "                is_in_array = { sov_national_obligations_unlocked_indexes = %s }\n" % i
            scripted_loc += "            }\n"
            scripted_loc += "        }\n"
            scripted_loc += "        localization_key = GUI_NATIONAL_OBLIGATIONS_%s_UNLOCKED\n" % national_obligation.upper()
            scripted_loc += "    }\n"
            scripted_loc += "    text = {\n"
            scripted_loc += "        localization_key = GUI_NATIONAL_OBLIGATIONS_%s_NOT_UNLOCKED\n" % national_obligation.upper()
            scripted_loc += "    }\n"
            scripted_loc += "}\n"
            i += 1

            f.write(scripted_loc)

        print("Success", end="\n\n")
        print("Generating localisation...")
        f.write("\n# Localisation\n")

        i = 1
        for national_obligation in national_obligations:
            loc = " GUI_NATIONAL_OBLIGATIONS_INDEX_%s_SELECTED:0 \"GFX_national_obligations_%s_gui\"\n" % (i, national_obligation)
            i += 1

            f.write(loc)

        i = 1
        for national_obligation in national_obligations:
            title = national_obligation.replace("_", " ").title()
            loc = " GUI_NATIONAL_OBLIGATIONS_INDEX_%s_SELECTED_TITLE:0 \"§O%s§!\"\n" % (i, title)
            i += 1

            f.write(loc)

        i = 1
        for national_obligation in national_obligations:
            loc = " GUI_NATIONAL_OBLIGATIONS_INDEX_%s_SELECTED_ICON:0 \"GFX_national_obligations_%s_icon\"\n" % (i, national_obligation)
            i += 1

            f.write(loc)

        i = 1
        for national_obligation in national_obligations:
            title = national_obligation.replace("_", " ").title()
            loc = " GUI_NATIONAL_OBLIGATIONS_%s_SELECTED:0 \"§O%s§!\"\n" % (national_obligation.upper(), title)
            loc += " GUI_NATIONAL_OBLIGATIONS_%s_UNLOCKED:0 \"§Y%s§!\"\n" % (national_obligation.upper(), title)
            loc += " GUI_NATIONAL_OBLIGATIONS_%s_NOT_UNLOCKED:0 \"§g%s§!\"\n" % (national_obligation.upper(), title)
            i += 1

            f.write(loc)

        i = 1
        for national_obligation in national_obligations:
            title = national_obligation.replace("_", " ").title()
            loc = " LOC_sov_national_obligations_nav_%s:0 \"[THIS.GetCurrentSelectedIndexNationalObligationsNav%sTitle]\"\n" % (national_obligation, title.replace(" ", ""))
            i += 1

            f.write(loc)

        print("Success", end="\n\n")
        print("Generating scripted gui...")
        f.write("\n# Scripted GUI")

        i = 1
        for national_obligation in national_obligations:
            title = national_obligation.replace("_", " ").title()
            scripted_gui = "\nsov_national_obligations_nav_%s = {\n" % (national_obligation)
            scripted_gui += "    image = [THIS.GetCurrentSelectedIndexNationalObligationsNav%s]\n" % (title.replace(" ", ""))
            scripted_gui += "}\n"
            i += 1

            f.write(scripted_gui)

        print("Success", end="\n\n")
        print("Generating individual GUI for each national obliations")

        national_obligations_with_options = zip(national_obligations, national_obligations_options)
        i = 1
        for national_obligation, national_obligation_options in national_obligations_with_options:
            title = national_obligation.replace("_", " ").title()
            print("Generating %s with %s option%s..." % (title, national_obligation_options, 's' if national_obligation_options > 1 else ''))
            
            match national_obligation_options:
                case 1:
                    gui = f"""
    #{ title }
    containerWindowType = {{
        name = "sov_national_obligations_{ national_obligation }_view"
        position = {{ x = 0 y = 0 }}
        size = {{ width = 1000 height = 800 }}
        orientation = center
        origo = center
        moveable = no
        click_to_front = no
        clipping = no
        fade_type = linear
        fade_time = 500

        buttonType = {{
            name = "sov_national_obligations_{ national_obligation }_confirm_button"
            position = {{ x = @CONFIRM_BUTTON_X y = @CONFIRM_BUTTON_Y }}
            orientation = "CENTER"
            spriteType = "GFX_national_obligations_confirm_button_gui"
            shortcut = "RETURN"
            buttonText = LOC_sov_national_obligations_{ national_obligation }_confirm_button
            buttonFont = cg_18b
            pdx_tooltip = LOC_sov_national_obligations_{ national_obligation }_confirm_button_tt
            alwaystransparent = no
        }}

        #Option 1
        containerWindowType = {{
            name = "sov_national_obligations_{ national_obligation }_first_option"
            position = {{ x = @ONE_OPTION_X y = @ONE_OPTION_Y }}
            size = {{ width = 250 height = 600 }}
            orientation = center
            origo = center
            moveable = no
            click_to_front = no
            clipping = yes

            iconType = {{
                name = "sov_national_obligations_{ national_obligation }_first_option_bg"
                position = {{ x = 0 y = -20 }}
                orientation = center
                alwaystransparent = yes
                centerposition = yes
            }}

            instantTextBoxType = {{
                name = "sov_national_obligations_{ national_obligation }_first_option_quote"
                position = {{ x = @QUOTE_OPTION_X y = @QUOTE_OPTION_Y }}
                orientation = center
                text = LOC_sov_national_obligations_{ national_obligation }_first_option_quote
                font = hoi4_typewriter22
                format = centre
                maxHeight = 160
                fixedsize = yes
                alwaystransparent = yes
            }}

            instantTextBoxType = {{
                name = "sov_national_obligations_{ national_obligation }_first_option_text"
                position = {{ x = @TOOLTIP_OPTION_X y = @TOOLTIP_OPTION_Y }}
                orientation = center
                text = LOC_sov_national_obligations_{ national_obligation }_first_option_text
                font = hoi_16mbs
                format = centre
                maxHeight = 170
                fixedsize = yes
                alwaystransparent = yes
            }}

            instantTextBoxType = {{
                name = "sov_national_obligations_{ national_obligation }_first_option_trigger"
                position = {{ x = @TRIGGER_OPTION_X y = @TRIGGER_OPTION_Y }}
                orientation = center
                text = LOC_sov_national_obligations_{ national_obligation }_first_option_trigger
                font = hoi_16mbs
                format = centre
                maxHeight = 65
                fixedsize = yes
                alwaystransparent = yes
            }}

            iconType = {{
                name = "sov_national_obligations_{ national_obligation }_first_option_glow"
                position = {{ x = @FOCUS_BUTTON_GLOW_X y = @FOCUS_BUTTON_GLOW_Y }}
                orientation = center
                quadTextureSprite = "GFX_national_obligations_option_icons_glow"
                scale = 1.2
            }}

            buttonType = {{
                name = "sov_national_obligations_{ national_obligation }_first_option_button"
                position = {{ x = @FOCUS_BUTTON_X y = @FOCUS_BUTTON_Y }}
                orientation = center
                spriteType = "GFX_{ national_obligation }_option_first_button_gui"
                shortcut = "1"
                buttonText = ""
                buttonFont = cg_18b
            }}
        }}
    }}
                        """
                case 2:
                    gui = f"""
    #{ title }
    containerWindowType = {{
        name = "sov_national_obligations_{ national_obligation }_view"
        position = {{ x = 0 y = 0 }}
        size = {{ width = 1000 height = 800 }}
        orientation = center
        origo = center
        moveable = no
        click_to_front = no
        clipping = no
        fade_type = linear
        fade_time = 500

        buttonType = {{
            name = "sov_national_obligations_{ national_obligation }_confirm_button"
            position = {{ x = @CONFIRM_BUTTON_X y = @CONFIRM_BUTTON_Y }}
            orientation = "CENTER"
            spriteType = "GFX_national_obligations_confirm_button_gui"
            shortcut = "RETURN"
            buttonText = LOC_sov_national_obligations_{ national_obligation }_confirm_button
            buttonFont = cg_18b
            pdx_tooltip = LOC_sov_national_obligations_{ national_obligation }_confirm_button_tt
            alwaystransparent = no
        }}

        #Option 1
        containerWindowType = {{
            name = "sov_national_obligations_{ national_obligation }_first_option"
            position = {{ x = @TWO_OPTION_FIRST_X y = @TWO_OPTION_FIRST_Y }}
            size = {{ width = 250 height = 600 }}
            orientation = center
            origo = center
            moveable = no
            click_to_front = no
            clipping = yes

            iconType = {{
                name = "sov_national_obligations_{ national_obligation }_first_option_bg"
                position = {{ x = 0 y = -20 }}
                orientation = center
                alwaystransparent = yes
                centerposition = yes
            }}

            instantTextBoxType = {{
                name = "sov_national_obligations_{ national_obligation }_first_option_quote"
                position = {{ x = @QUOTE_OPTION_X y = @QUOTE_OPTION_Y }}
                orientation = center
                text = LOC_sov_national_obligations_{ national_obligation }_first_option_quote
                font = hoi4_typewriter22
                format = centre
                maxHeight = 160
                fixedsize = yes
                alwaystransparent = yes
            }}

            instantTextBoxType = {{
                name = "sov_national_obligations_{ national_obligation }_first_option_text"
                position = {{ x = @TOOLTIP_OPTION_X y = @TOOLTIP_OPTION_Y }}
                orientation = center
                text = LOC_sov_national_obligations_{ national_obligation }_first_option_text
                font = hoi_16mbs
                format = centre
                maxHeight = 170
                fixedsize = yes
                alwaystransparent = yes
            }}

            instantTextBoxType = {{
                name = "sov_national_obligations_{ national_obligation }_first_option_trigger"
                position = {{ x = @TRIGGER_OPTION_X y = @TRIGGER_OPTION_Y }}
                orientation = center
                text = LOC_sov_national_obligations_{ national_obligation }_first_option_trigger
                font = hoi_16mbs
                format = centre
                maxHeight = 65
                fixedsize = yes
                alwaystransparent = yes
            }}

            iconType = {{
                name = "sov_national_obligations_{ national_obligation }_first_option_glow"
                position = {{ x = @FOCUS_BUTTON_GLOW_X y = @FOCUS_BUTTON_GLOW_Y }}
                orientation = center
                quadTextureSprite = "GFX_national_obligations_option_icons_glow"
                scale = 1.2
            }}

            buttonType = {{
                name = "sov_national_obligations_{ national_obligation }_first_option_button"
                position = {{ x = @FOCUS_BUTTON_X y = @FOCUS_BUTTON_Y }}
                orientation = center
                spriteType = "GFX_{ national_obligation }_option_first_button_gui"
                shortcut = "1"
                buttonText = ""
                buttonFont = cg_18b
            }}
        }}

        #Option 2
        containerWindowType = {{
            name = "sov_national_obligations_{ national_obligation }_second_option"
            position = {{ x = @TWO_OPTION_SECOND_X y = @TWO_OPTION_SECOND_Y }}
            size = {{ width = 250 height = 600 }}
            orientation = center
            origo = center
            moveable = no
            click_to_front = no
            clipping = yes

            iconType = {{
                name = "sov_national_obligations_{ national_obligation }_second_option_bg"
                position = {{ x = 0 y = -20 }}
                orientation = center
                alwaystransparent = yes
                centerposition = yes
            }}

            instantTextBoxType = {{
                name = "sov_national_obligations_{ national_obligation }_second_option_quote"
                position = {{ x = @QUOTE_OPTION_X y = @QUOTE_OPTION_Y }}
                orientation = center
                text = LOC_sov_national_obligations_{ national_obligation }_second_option_quote
                font = hoi4_typewriter22
                format = centre
                maxHeight = 160
                fixedsize = yes
                alwaystransparent = yes
            }}

            instantTextBoxType = {{
                name = "sov_national_obligations_{ national_obligation }_second_option_text"
                position = {{ x = @TOOLTIP_OPTION_X y = @TOOLTIP_OPTION_Y }}
                orientation = center
                text = LOC_sov_national_obligations_{ national_obligation }_second_option_text
                font = hoi_16mbs
                format = centre
                maxHeight = 170
                fixedsize = yes
                alwaystransparent = yes
            }}

            instantTextBoxType = {{
                name = "sov_national_obligations_{ national_obligation }_second_option_trigger"
                position = {{ x = @TRIGGER_OPTION_X y = @TRIGGER_OPTION_Y }}
                orientation = center
                text = LOC_sov_national_obligations_{ national_obligation }_second_option_trigger
                font = hoi_16mbs
                format = centre
                maxHeight = 65
                fixedsize = yes
                alwaystransparent = yes
            }}

            iconType = {{
                name = "sov_national_obligations_{ national_obligation }_second_option_glow"
                position = {{ x = @FOCUS_BUTTON_GLOW_X y = @FOCUS_BUTTON_GLOW_Y }}
                orientation = center
                quadTextureSprite = "GFX_national_obligations_option_icons_glow"
                scale = 1.2
            }}

            buttonType = {{
                name = "sov_national_obligations_{ national_obligation }_second_option_button"
                position = {{ x = @FOCUS_BUTTON_X y = @FOCUS_BUTTON_Y }}
                orientation = center
                spriteType = "GFX_{ national_obligation }_option_second_button_gui"
                shortcut = "2"
                buttonText = ""
                buttonFont = cg_18b
            }}
        }}
    }}
                        """
                case 3:
                    gui = f"""
    #{ title }
    containerWindowType = {{
        name = "sov_national_obligations_{ national_obligation }_view"
        position = {{ x = 0 y = 0 }}
        size = {{ width = 1000 height = 800 }}
        orientation = center
        origo = center
        moveable = no
        click_to_front = no
        clipping = no
        fade_type = linear
        fade_time = 500

        buttonType = {{
            name = "sov_national_obligations_{ national_obligation }_confirm_button"
            position = {{ x = @CONFIRM_BUTTON_X y = @CONFIRM_BUTTON_Y }}
            orientation = "CENTER"
            spriteType = "GFX_national_obligations_confirm_button_gui"
            shortcut = "RETURN"
            buttonText = LOC_sov_national_obligations_{ national_obligation }_confirm_button
            buttonFont = cg_18b
            pdx_tooltip = LOC_sov_national_obligations_{ national_obligation }_confirm_button_tt
            alwaystransparent = no
        }}

        #Option 1
        containerWindowType = {{
            name = "sov_national_obligations_{ national_obligation }_first_option"
            position = {{ x = @THREE_OPTION_FIRST_X y = @THREE_OPTION_FIRST_Y }}
            size = {{ width = 250 height = 600 }}
            orientation = center
            origo = center
            moveable = no
            click_to_front = no
            clipping = yes

            iconType = {{
                name = "sov_national_obligations_{ national_obligation }_first_option_bg"
                position = {{ x = 0 y = -20 }}
                orientation = center
                alwaystransparent = yes
                centerposition = yes
            }}

            instantTextBoxType = {{
                name = "sov_national_obligations_{ national_obligation }_first_option_quote"
                position = {{ x = @QUOTE_OPTION_X y = @QUOTE_OPTION_Y }}
                orientation = center
                text = LOC_sov_national_obligations_{ national_obligation }_first_option_quote
                font = hoi4_typewriter22
                format = centre
                maxHeight = 160
                fixedsize = yes
                alwaystransparent = yes
            }}

            instantTextBoxType = {{
                name = "sov_national_obligations_{ national_obligation }_first_option_text"
                position = {{ x = @TOOLTIP_OPTION_X y = @TOOLTIP_OPTION_Y }}
                orientation = center
                text = LOC_sov_national_obligations_{ national_obligation }_first_option_text
                font = hoi_16mbs
                format = centre
                maxHeight = 170
                fixedsize = yes
                alwaystransparent = yes
            }}

            instantTextBoxType = {{
                name = "sov_national_obligations_{ national_obligation }_first_option_trigger"
                position = {{ x = @TRIGGER_OPTION_X y = @TRIGGER_OPTION_Y }}
                orientation = center
                text = LOC_sov_national_obligations_{ national_obligation }_first_option_trigger
                font = hoi_16mbs
                format = centre
                maxHeight = 65
                fixedsize = yes
                alwaystransparent = yes
            }}

            iconType = {{
                name = "sov_national_obligations_{ national_obligation }_first_option_glow"
                position = {{ x = @FOCUS_BUTTON_GLOW_X y = @FOCUS_BUTTON_GLOW_Y }}
                orientation = center
                quadTextureSprite = "GFX_national_obligations_option_icons_glow"
                scale = 1.2
            }}

            buttonType = {{
                name = "sov_national_obligations_{ national_obligation }_first_option_button"
                position = {{ x = @FOCUS_BUTTON_X y = @FOCUS_BUTTON_Y }}
                orientation = center
                spriteType = "GFX_{ national_obligation }_option_first_button_gui"
                shortcut = "1"
                buttonText = ""
                buttonFont = cg_18b
            }}
        }}

        #Option 2
        containerWindowType = {{
            name = "sov_national_obligations_{ national_obligation }_second_option"
            position = {{ x = @THREE_OPTION_SECOND_X y = @THREE_OPTION_SECOND_Y }}
            size = {{ width = 250 height = 600 }}
            orientation = center
            origo = center
            moveable = no
            click_to_front = no
            clipping = yes

            iconType = {{
                name = "sov_national_obligations_{ national_obligation }_second_option_bg"
                position = {{ x = 0 y = -20 }}
                orientation = center
                alwaystransparent = yes
                centerposition = yes
            }}

            instantTextBoxType = {{
                name = "sov_national_obligations_{ national_obligation }_second_option_quote"
                position = {{ x = @QUOTE_OPTION_X y = @QUOTE_OPTION_Y }}
                orientation = center
                text = LOC_sov_national_obligations_{ national_obligation }_second_option_quote
                font = hoi4_typewriter22
                format = centre
                maxHeight = 160
                fixedsize = yes
                alwaystransparent = yes
            }}

            instantTextBoxType = {{
                name = "sov_national_obligations_{ national_obligation }_second_option_text"
                position = {{ x = @TOOLTIP_OPTION_X y = @TOOLTIP_OPTION_Y }}
                orientation = center
                text = LOC_sov_national_obligations_{ national_obligation }_second_option_text
                font = hoi_16mbs
                format = centre
                maxHeight = 170
                fixedsize = yes
                alwaystransparent = yes
            }}

            instantTextBoxType = {{
                name = "sov_national_obligations_{ national_obligation }_second_option_trigger"
                position = {{ x = @TRIGGER_OPTION_X y = @TRIGGER_OPTION_Y }}
                orientation = center
                text = LOC_sov_national_obligations_{ national_obligation }_second_option_trigger
                font = hoi_16mbs
                format = centre
                maxHeight = 65
                fixedsize = yes
                alwaystransparent = yes
            }}

            iconType = {{
                name = "sov_national_obligations_{ national_obligation }_second_option_glow"
                position = {{ x = @FOCUS_BUTTON_GLOW_X y = @FOCUS_BUTTON_GLOW_Y }}
                orientation = center
                quadTextureSprite = "GFX_national_obligations_option_icons_glow"
                scale = 1.2
            }}

            buttonType = {{
                name = "sov_national_obligations_{ national_obligation }_second_option_button"
                position = {{ x = @FOCUS_BUTTON_X y = @FOCUS_BUTTON_Y }}
                orientation = center
                spriteType = "GFX_{ national_obligation }_option_second_button_gui"
                shortcut = "2"
                buttonText = ""
                buttonFont = cg_18b
            }}
        }}

        #Option 3
        containerWindowType = {{
            name = "sov_national_obligations_{ national_obligation }_third_option"
            position = {{ x = @THREE_OPTION_THIRD_X y = @THREE_OPTION_THIRD_Y }}
            size = {{ width = 250 height = 600 }}
            orientation = center
            origo = center
            moveable = no
            click_to_front = no
            clipping = yes

            iconType = {{
                name = "sov_national_obligations_{ national_obligation }_third_option_bg"
                position = {{ x = 0 y = -20 }}
                orientation = center
                alwaystransparent = yes
                centerposition = yes
            }}

            instantTextBoxType = {{
                name = "sov_national_obligations_{ national_obligation }_third_option_quote"
                position = {{ x = @QUOTE_OPTION_X y = @QUOTE_OPTION_Y }}
                orientation = center
                text = LOC_sov_national_obligations_{ national_obligation }_third_option_quote
                font = hoi4_typewriter22
                format = centre
                maxHeight = 160
                fixedsize = yes
                alwaystransparent = yes
            }}

            instantTextBoxType = {{
                name = "sov_national_obligations_{ national_obligation }_third_option_text"
                position = {{ x = @TOOLTIP_OPTION_X y = @TOOLTIP_OPTION_Y }}
                orientation = center
                text = LOC_sov_national_obligations_{ national_obligation }_third_option_text
                font = hoi_16mbs
                format = centre
                maxHeight = 170
                fixedsize = yes
                alwaystransparent = yes
            }}

            instantTextBoxType = {{
                name = "sov_national_obligations_{ national_obligation }_third_option_trigger"
                position = {{ x = @TRIGGER_OPTION_X y = @TRIGGER_OPTION_Y }}
                orientation = center
                text = LOC_sov_national_obligations_{ national_obligation }_third_option_trigger
                font = hoi_16mbs
                format = centre
                maxHeight = 65
                fixedsize = yes
                alwaystransparent = yes
            }}

            iconType = {{
                name = "sov_national_obligations_{ national_obligation }_third_option_glow"
                position = {{ x = @FOCUS_BUTTON_GLOW_X y = @FOCUS_BUTTON_GLOW_Y }}
                orientation = center
                quadTextureSprite = "GFX_national_obligations_option_icons_glow"
                scale = 1.2
            }}

            buttonType = {{
                name = "sov_national_obligations_{ national_obligation }_third_option_button"
                position = {{ x = @FOCUS_BUTTON_X y = @FOCUS_BUTTON_Y }}
                orientation = center
                spriteType = "GFX_{ national_obligation }_option_third_button_gui"
                shortcut = "3"
                buttonText = ""
                buttonFont = cg_18b
            }}
        }}
    }}
                        """
                case _:
                    print("Warning : No options set for %s" % title)
                    
            i += 1
            f.write(gui)

        national_obligations_with_options = zip(national_obligations, national_obligations_options)
        i = 1
        for national_obligation, national_obligation_options in national_obligations_with_options:
            title = national_obligation.replace("_", " ").title()
            print("Generating scripted GUI for %s..." % (title))
            
            match national_obligation_options:
                case 1:
                    scripted_gui = f"""
    #{ title }
    sov_national_obligations_{ national_obligation }_scripted_gui = {{
        window_name = "sov_national_obligations_{ national_obligation }_view"
        context_type = player_context
        parent_window_name = "sov_national_obligations_scripted_gui_window"

        visible = {{
            check_variable = {{
                var = sov_national_obligations_selected_index
                value = { i }
                compare = equals
            }}
        }}

        properties = {{
            sov_national_obligations_{ national_obligation }_first_option_bg = {{
                image = [THIS.GetCurrentStatusFirstOption{ title.replace(" ", "") }]
            }}
        }}

        effects = {{
            sov_national_obligations_{ national_obligation }_confirm_button_click {{
                THIS = {{
                    #TODO
                    set_country_flag = { national_obligation }_confirmed
                    if = {{
                        limit = {{
                            has_country_flag = sov_open_national_obligations_help
                        }}
                        clr_country_flag = sov_open_national_obligations_help
                    }}
                    if = {{
                        limit = {{
                            has_country_flag = sov_debug_national_obligations
                        }}
                        clr_country_flag = sov_debug_national_obligations
                    }}
                    if = {{
                        limit = {{
                            has_country_flag = sov_open_national_obligations
                        }}
                        clr_country_flag = sov_open_national_obligations
                    }}
                }}
            }}

            sov_national_obligations_{ national_obligation }_first_option_button_click {{
                THIS = {{
                    if = {{
                        limit = {{
                            check_variable = {{
                                sov_national_obligations_{ national_obligation }_selected_index = 1
                            }}
                        }}
                        set_variable = {{
                            sov_national_obligations_{ national_obligation }_selected_index = 0
                        }}
                    }}
                    else = {{
                        set_variable = {{
                            sov_national_obligations_{ national_obligation }_selected_index = 1
                        }}
                    }}
                }}
            }}
        }}

        triggers = {{
            sov_national_obligations_{ national_obligation }_confirm_button_click_enabled = {{
                THIS = {{
                    check_variable = {{
                        sov_national_obligations_{ national_obligation }_selected_index = 1
                    }}
                    NOT = {{
                        has_country_flag = { national_obligation }_confirmed
                    }}
                }}
            }}

            sov_national_obligations_{ national_obligation }_first_option_glow_visible = {{
                check_variable = {{
                    sov_national_obligations_{ national_obligation }_selected_index = 1
                }}
            }}

            sov_national_obligations_{ national_obligation }_first_option_button_click_enabled = {{
                THIS = {{
                    #TODO
                    NOT = {{
                        has_country_flag = { national_obligation }_confirmed
                    }}
                }}
            }}
        }}
    }}
                    """
                case 2:
                    scripted_gui = f"""
    #{ title }
    sov_national_obligations_{ national_obligation }_scripted_gui = {{
        window_name = "sov_national_obligations_{ national_obligation }_view"
        context_type = player_context
        parent_window_name = "sov_national_obligations_scripted_gui_window"

        visible = {{
            check_variable = {{
                var = sov_national_obligations_selected_index
                value = { i }
                compare = equals
            }}
        }}

        properties = {{
            sov_national_obligations_{ national_obligation }_first_option_bg = {{
                image = [THIS.GetCurrentStatusFirstOption{ title.replace(" ", "") }]
            }}

            sov_national_obligations_{ national_obligation }_second_option_bg = {{
                image = [THIS.GetCurrentStatusSecondOption{ title.replace(" ", "") }]
            }}
        }}

        effects = {{
            sov_national_obligations_{ national_obligation }_confirm_button_click {{
                THIS = {{
                    #TODO
                    set_country_flag = { national_obligation }_confirmed
                    if = {{
                        limit = {{
                            has_country_flag = sov_open_national_obligations_help
                        }}
                        clr_country_flag = sov_open_national_obligations_help
                    }}
                    if = {{
                        limit = {{
                            has_country_flag = sov_debug_national_obligations
                        }}
                        clr_country_flag = sov_debug_national_obligations
                    }}
                    if = {{
                        limit = {{
                            has_country_flag = sov_open_national_obligations
                        }}
                        clr_country_flag = sov_open_national_obligations
                    }}
                }}
            }}

            sov_national_obligations_{ national_obligation }_first_option_button_click {{
                THIS = {{
                    if = {{
                        limit = {{
                            check_variable = {{
                                sov_national_obligations_{ national_obligation }_selected_index = 1
                            }}
                        }}
                        set_variable = {{
                            sov_national_obligations_{ national_obligation }_selected_index = 0
                        }}
                    }}
                    else = {{
                        set_variable = {{
                            sov_national_obligations_{ national_obligation }_selected_index = 1
                        }}
                    }}
                }}
            }}

            sov_national_obligations_{ national_obligation }_second_option_button_click {{
                THIS = {{
                    if = {{
                        limit = {{
                            check_variable = {{
                                sov_national_obligations_{ national_obligation }_selected_index = 2
                            }}
                        }}
                        set_variable = {{
                            sov_national_obligations_{ national_obligation }_selected_index = 0
                        }}
                    }}
                    else = {{
                        set_variable = {{
                            sov_national_obligations_{ national_obligation }_selected_index = 2
                        }}
                    }}
                }}
            }}
        }}

        triggers = {{
            sov_national_obligations_{ national_obligation }_confirm_button_click_enabled = {{
                THIS = {{
                    OR = {{
                        check_variable = {{
                            sov_national_obligations_{ national_obligation }_selected_index = 1
                        }}
                        check_variable = {{
                            sov_national_obligations_{ national_obligation }_selected_index = 2
                        }}
                    }}
                    NOT = {{
                        has_country_flag = { national_obligation }_confirmed
                    }}
                }}
            }}

            sov_national_obligations_{ national_obligation }_first_option_glow_visible = {{
                check_variable = {{
                    sov_national_obligations_{ national_obligation }_selected_index = 1
                }}
            }}

            sov_national_obligations_{ national_obligation }_first_option_button_click_enabled = {{
                THIS = {{
                    #TODO
                    NOT = {{
                        has_country_flag = { national_obligation }_confirmed
                    }}
                }}
            }}

            sov_national_obligations_{ national_obligation }_second_option_glow_visible = {{
                check_variable = {{
                    sov_national_obligations_{ national_obligation }_selected_index = 2
                }}
            }}

            sov_national_obligations_{ national_obligation }_second_option_button_click_enabled = {{
                THIS = {{
                    #TODO
                    NOT = {{
                        has_country_flag = { national_obligation }_confirmed
                    }}
                }}
            }}
        }}
    }}
                    """
                case 3:
                    scripted_gui = f"""
    #{ title }
    sov_national_obligations_{ national_obligation }_scripted_gui = {{
        window_name = "sov_national_obligations_{ national_obligation }_view"
        context_type = player_context
        parent_window_name = "sov_national_obligations_scripted_gui_window"

        visible = {{
            check_variable = {{
                var = sov_national_obligations_selected_index
                value = { i }
                compare = equals
            }}
        }}

        properties = {{
            sov_national_obligations_{ national_obligation }_first_option_bg = {{
                image = [THIS.GetCurrentStatusFirstOption{ title.replace(" ", "") }]
            }}

            sov_national_obligations_{ national_obligation }_second_option_bg = {{
                image = [THIS.GetCurrentStatusSecondOption{ title.replace(" ", "") }]
            }}

            sov_national_obligations_{ national_obligation }_third_option_bg = {{
                image = [THIS.GetCurrentStatusThirdOption{ title.replace(" ", "") }]
            }}
        }}

        effects = {{
            sov_national_obligations_{ national_obligation }_confirm_button_click {{
                THIS = {{
                    #TODO
                    set_country_flag = { national_obligation }_confirmed
                    if = {{
                        limit = {{
                            has_country_flag = sov_open_national_obligations_help
                        }}
                        clr_country_flag = sov_open_national_obligations_help
                    }}
                    if = {{
                        limit = {{
                            has_country_flag = sov_debug_national_obligations
                        }}
                        clr_country_flag = sov_debug_national_obligations
                    }}
                    if = {{
                        limit = {{
                            has_country_flag = sov_open_national_obligations
                        }}
                        clr_country_flag = sov_open_national_obligations
                    }}
                }}
            }}

            sov_national_obligations_{ national_obligation }_first_option_button_click {{
                THIS = {{
                    if = {{
                        limit = {{
                            check_variable = {{
                                sov_national_obligations_{ national_obligation }_selected_index = 1
                            }}
                        }}
                        set_variable = {{
                            sov_national_obligations_{ national_obligation }_selected_index = 0
                        }}
                    }}
                    else = {{
                        set_variable = {{
                            sov_national_obligations_{ national_obligation }_selected_index = 1
                        }}
                    }}
                }}
            }}

            sov_national_obligations_{ national_obligation }_second_option_button_click {{
                THIS = {{
                    if = {{
                        limit = {{
                            check_variable = {{
                                sov_national_obligations_{ national_obligation }_selected_index = 2
                            }}
                        }}
                        set_variable = {{
                            sov_national_obligations_{ national_obligation }_selected_index = 0
                        }}
                    }}
                    else = {{
                        set_variable = {{
                            sov_national_obligations_{ national_obligation }_selected_index = 2
                        }}
                    }}
                }}
            }}

            sov_national_obligations_{ national_obligation }_third_option_button_click {{
                THIS = {{
                    if = {{
                        limit = {{
                            check_variable = {{
                                sov_national_obligations_{ national_obligation }_selected_index = 3
                            }}
                        }}
                        set_variable = {{
                            sov_national_obligations_{ national_obligation }_selected_index = 0
                        }}
                    }}
                    else = {{
                        set_variable = {{
                            sov_national_obligations_{ national_obligation }_selected_index = 3
                        }}
                    }}
                }}
            }}
        }}

        triggers = {{
            sov_national_obligations_{ national_obligation }_confirm_button_click_enabled = {{
                THIS = {{
                    OR = {{
                        check_variable = {{
                            sov_national_obligations_{ national_obligation }_selected_index = 1
                        }}
                        check_variable = {{
                            sov_national_obligations_{ national_obligation }_selected_index = 2
                        }}
                        check_variable = {{
                            sov_national_obligations_{ national_obligation }_selected_index = 3
                        }}
                    }}
                    NOT = {{
                        has_country_flag = { national_obligation }_confirmed
                    }}
                }}
            }}

            sov_national_obligations_{ national_obligation }_first_option_glow_visible = {{
                check_variable = {{
                    sov_national_obligations_{ national_obligation }_selected_index = 1
                }}
            }}

            sov_national_obligations_{ national_obligation }_first_option_button_click_enabled = {{
                THIS = {{
                    #TODO
                    NOT = {{
                        has_country_flag = { national_obligation }_confirmed
                    }}
                }}
            }}

            sov_national_obligations_{ national_obligation }_second_option_glow_visible = {{
                check_variable = {{
                    sov_national_obligations_{ national_obligation }_selected_index = 2
                }}
            }}

            sov_national_obligations_{ national_obligation }_second_option_button_click_enabled = {{
                THIS = {{
                    #TODO
                    NOT = {{
                        has_country_flag = { national_obligation }_confirmed
                    }}
                }}
            }}

            sov_national_obligations_{ national_obligation }_third_option_glow_visible = {{
                check_variable = {{
                    sov_national_obligations_{ national_obligation }_selected_index = 3
                }}
            }}

            sov_national_obligations_{ national_obligation }_third_option_button_click_enabled = {{
                THIS = {{
                    #TODO
                    NOT = {{
                        has_country_flag = { national_obligation }_confirmed
                    }}
                }}
            }}
        }}
    }}
                    """
                case _:
                    print("Warning : No options set for %s" % title)
            i += 1
            f.write(scripted_gui)

        national_obligations_with_options = zip(national_obligations, national_obligations_options)
        i = 1
        for national_obligation, national_obligation_options in national_obligations_with_options:
            title = national_obligation.replace("_", " ").title()
            print("Generating scripted localisation for %s..." % (title))
            
            match national_obligation_options:
                case 1:
                    scripted_localisation = f"""
#{ title }
defined_text = {{
	name = GetCurrentStatusFirstOption{ title.replace(" ", "")}
	text = {{
		trigger = {{
			THIS = {{
                check_variable = {{
                    sov_national_obligations_{ national_obligation }_selected_index = 1
                }}
            }}
		}}
		localization_key = GUI_NATIONAL_OBLIGATIONS_OPTION_SELECTED
	}}
	text = {{
		localization_key = GUI_NATIONAL_OBLIGATIONS_OPTION_NON_SELECTED
	}}
}}
                    """
                case 2:
                    scripted_localisation = f"""
#{ title }
defined_text = {{
	name = GetCurrentStatusFirstOption{ title.replace(" ", "")}
	text = {{
		trigger = {{
			THIS = {{
                check_variable = {{
                    sov_national_obligations_{ national_obligation }_selected_index = 1
                }}
            }}
		}}
		localization_key = GUI_NATIONAL_OBLIGATIONS_OPTION_SELECTED
	}}
	text = {{
		localization_key = GUI_NATIONAL_OBLIGATIONS_OPTION_NON_SELECTED
	}}
}}

defined_text = {{
	name = GetCurrentStatusSecondOption{ title.replace(" ", "")}
	text = {{
		trigger = {{
			THIS = {{
                check_variable = {{
                    sov_national_obligations_{ national_obligation }_selected_index = 2
                }}
            }}
		}}
		localization_key = GUI_NATIONAL_OBLIGATIONS_OPTION_SELECTED
	}}
	text = {{
		localization_key = GUI_NATIONAL_OBLIGATIONS_OPTION_NON_SELECTED
	}}
}}
                    """
                case 3:
                    scripted_localisation = f"""
#{ title }
defined_text = {{
	name = GetCurrentStatusFirstOption{ title.replace(" ", "")}
	text = {{
		trigger = {{
			THIS = {{
                check_variable = {{
                    sov_national_obligations_{ national_obligation }_selected_index = 1
                }}
            }}
		}}
		localization_key = GUI_NATIONAL_OBLIGATIONS_OPTION_SELECTED
	}}
	text = {{
		localization_key = GUI_NATIONAL_OBLIGATIONS_OPTION_NON_SELECTED
	}}
}}

defined_text = {{
	name = GetCurrentStatusSecondOption{ title.replace(" ", "")}
	text = {{
		trigger = {{
			THIS = {{
                check_variable = {{
                    sov_national_obligations_{ national_obligation }_selected_index = 2
                }}
            }}
		}}
		localization_key = GUI_NATIONAL_OBLIGATIONS_OPTION_SELECTED
	}}
	text = {{
		localization_key = GUI_NATIONAL_OBLIGATIONS_OPTION_NON_SELECTED
	}}
}}

defined_text = {{
	name = GetCurrentStatusThirdOption{ title.replace(" ", "")}
	text = {{
		trigger = {{
			THIS = {{
                check_variable = {{
                    sov_national_obligations_{ national_obligation }_selected_index = 3
                }}
            }}
		}}
		localization_key = GUI_NATIONAL_OBLIGATIONS_OPTION_SELECTED
	}}
	text = {{
		localization_key = GUI_NATIONAL_OBLIGATIONS_OPTION_NON_SELECTED
	}}
}}
                    """
                case _:
                    print("Warning : No options set for %s" % title)

            i += 1
            f.write(scripted_localisation)

        national_obligations_with_options = zip(national_obligations, national_obligations_options)
        i = 1
        for national_obligation, national_obligation_options in national_obligations_with_options:
            title = national_obligation.replace("_", " ").title()
            print("Generating scripted localisation (triggers) for %s..." % (title))
            
            match national_obligation_options:
                case 1:
                    scripted_localisation = f"""
#{ title }
defined_text = {{
	name = GetTriggerStatusFirstOption{ title.replace(" ", "") }
	text = {{
		trigger = {{
			THIS = {{
                #TODO
            }}
		}}
		localization_key = LOC_sov_national_obligations_YES
	}}
	text = {{
		localization_key = LOC_sov_national_obligations_NO
	}}
}}
                    """
                case 2:
                    scripted_localisation = f"""
#{ title }
defined_text = {{
	name = GetTriggerStatusFirstOption{ title.replace(" ", "") }
	text = {{
		trigger = {{
			THIS = {{
                #TODO
            }}
		}}
		localization_key = LOC_sov_national_obligations_YES
	}}
	text = {{
		localization_key = LOC_sov_national_obligations_NO
	}}
}}

defined_text = {{
	name = GetTriggerStatusSecondOption{ title.replace(" ", "") }
	text = {{
		trigger = {{
			THIS = {{
                #TODO
            }}
		}}
		localization_key = LOC_sov_national_obligations_YES
	}}
	text = {{
		localization_key = LOC_sov_national_obligations_NO
	}}
}}
                    """
                case 3:
                    scripted_localisation = f"""
#{ title }
defined_text = {{
	name = GetTriggerStatusFirstOption{ title.replace(" ", "") }
	text = {{
		trigger = {{
			THIS = {{
                #TODO
            }}
		}}
		localization_key = LOC_sov_national_obligations_YES
	}}
	text = {{
		localization_key = LOC_sov_national_obligations_NO
	}}
}}

defined_text = {{
	name = GetTriggerStatusSecondOption{ title.replace(" ", "") }
	text = {{
		trigger = {{
			THIS = {{
                #TODO
            }}
		}}
		localization_key = LOC_sov_national_obligations_YES
	}}
	text = {{
		localization_key = LOC_sov_national_obligations_NO
	}}
}}

defined_text = {{
	name = GetTriggerStatusThirdOption{ title.replace(" ", "") }
	text = {{
		trigger = {{
			THIS = {{
                #TODO
            }}
		}}
		localization_key = LOC_sov_national_obligations_YES
	}}
	text = {{
		localization_key = LOC_sov_national_obligations_NO
	}}
}}
                    """
                case _:
                    print("Warning : No options set for %s" % title)
                    
            i += 1
            f.write(scripted_localisation)

        national_obligations_with_options = zip(national_obligations, national_obligations_options)
        i = 1
        for national_obligation, national_obligation_options in national_obligations_with_options:
            title = national_obligation.replace("_", " ").title()
            print("Generating localisation for %s..." % (title))
            
            match national_obligation_options:
                case 1:
                    localisation = f"""
 LOC_sov_national_obligations_{ national_obligation }_confirm_button:0 "Confirm"
 LOC_sov_national_obligations_{ national_obligation }_first_option_text:0 "WIP"
 LOC_sov_national_obligations_{ national_obligation }_first_option_quote:0 "§W\\"First quote here.\\"§!\\n§YQuote Author§!"
 LOC_sov_national_obligations_{ national_obligation }_first_option_trigger:0 "[THIS.GetTriggerStatusFirstOption{ title.replace(" ", "") }] WIP"
                    """
                case 2:
                    localisation = f"""
 LOC_sov_national_obligations_{ national_obligation }_confirm_button:0 "Confirm"
 LOC_sov_national_obligations_{ national_obligation }_first_option_text:0 "WIP"
 LOC_sov_national_obligations_{ national_obligation }_second_option_text:0 "WIP"
 LOC_sov_national_obligations_{ national_obligation }_first_option_quote:0 "§W\\"First quote here.\\"§!\\n§YQuote Author§!"
 LOC_sov_national_obligations_{ national_obligation }_second_option_quote:0 "§W\\"Second quote here.\\"§!\\n§YQuote Author§!"
 LOC_sov_national_obligations_{ national_obligation }_first_option_trigger:0 "[THIS.GetTriggerStatusFirstOption{ title.replace(" ", "") }] WIP"
 LOC_sov_national_obligations_{ national_obligation }_second_option_trigger:0 "[THIS.GetTriggerStatusSecondOption{ title.replace(" ", "") }] WIP"
                    """
                case 3:
                    localisation = f"""
 LOC_sov_national_obligations_{ national_obligation }_confirm_button:0 "Confirm"
 LOC_sov_national_obligations_{ national_obligation }_first_option_text:0 "WIP"
 LOC_sov_national_obligations_{ national_obligation }_second_option_text:0 "WIP"
 LOC_sov_national_obligations_{ national_obligation }_third_option_text:0 "WIP"
 LOC_sov_national_obligations_{ national_obligation }_first_option_quote:0 "§W\\"First quote here.\\"§!\\n§YQuote Author§!"
 LOC_sov_national_obligations_{ national_obligation }_second_option_quote:0 "§W\\"Second quote here.\\"§!\\n§YQuote Author§!"
 LOC_sov_national_obligations_{ national_obligation }_third_option_quote:0 "§W\\"Third quote here.\\"§!\\n§YQuote Author§!"
 LOC_sov_national_obligations_{ national_obligation }_first_option_trigger:0 "[THIS.GetTriggerStatusFirstOption{ title.replace(" ", "") }] WIP"
 LOC_sov_national_obligations_{ national_obligation }_second_option_trigger:0 "[THIS.GetTriggerStatusSecondOption{ title.replace(" ", "") }] WIP"
 LOC_sov_national_obligations_{ national_obligation }_third_option_trigger:0 "[THIS.GetTriggerStatusThirdOption{ title.replace(" ", "") }] WIP"
                    """
                case _:
                    print("Warning : No options set for %s" % title)
                    
            i += 1
            f.write(localisation)

        national_obligations_with_options = zip(national_obligations, national_obligations_options)
        i = 1
        for national_obligation, national_obligation_options in national_obligations_with_options:
            title = national_obligation.replace("_", " ").title()
            print("Generating GFX for %s..." % (title))
            
            match national_obligation_options:
                case 1:
                    gfx = f"""
    spriteType = {{
        name = "GFX_{ national_obligation }_option_first_button_gui"
        texturefile = "gfx/interface/scripted_gui/GFX_{ national_obligation }_first_option_button.dds"
    }}
                    """
                case 2:
                    gfx = f"""
    spriteType = {{
        name = "GFX_{ national_obligation }_option_first_button_gui"
        texturefile = "gfx/interface/scripted_gui/GFX_{ national_obligation }_first_option_button.dds"
    }}

    spriteType = {{
        name = "GFX_{ national_obligation }_option_second_button_gui"
        texturefile = "gfx/interface/scripted_gui/GFX_{ national_obligation }_second_option_button.dds"
    }}
                    """
                case 3:
                    gfx = f"""
    spriteType = {{
        name = "GFX_{ national_obligation }_option_first_button_gui"
        texturefile = "gfx/interface/scripted_gui/GFX_{ national_obligation }_first_option_button.dds"
    }}

    spriteType = {{
        name = "GFX_{ national_obligation }_option_second_button_gui"
        texturefile = "gfx/interface/scripted_gui/GFX_{ national_obligation }_second_option_button.dds"
    }}

    spriteType = {{
        name = "GFX_{ national_obligation }_option_third_button_gui"
        texturefile = "gfx/interface/scripted_gui/GFX_{ national_obligation }_third_option_button.dds"
    }}
                    """
                case _:
                    print("Warning : No options set for %s" % title)
                    
            i += 1
            f.write(gfx)

        print("Successfully generated individual GUIs")
        f.close

    except Exception:
        print("Something went wrong...")
        print(traceback.format_exc())
